---
Organizations:
  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"
    AnchorPeers:
      - Host: peer0.org1.example.com
        Port: 7051

  - &Org2
    Name: Org2MSP
    ID: Org2MSP
    MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org2MSP.admin')"
    AnchorPeers:
      - Host: peer0.org2.example.com
        Port: 8051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations: []
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('Org1MSP.admin', 'Org2MSP.admin')"
    LifecycleEndorsement:
      Type: Signature
      Rule: "OR('Org1MSP.peer', 'Org2MSP.peer')"
    Endorsement:
      Type: Signature
      Rule: "OR('Org1MSP.peer', 'Org2MSP.peer')"
    BlockValidation:
      Type: Signature
      Rule: "OR('Org1MSP.peer', 'Org2MSP.peer')"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  EtcdRaft:
    Consenters:
      - Host: orderer.example.com
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('Org1MSP.admin', 'Org2MSP.admin')"
    BlockValidation:
      Type: Signature
      Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('Org1MSP.admin', 'Org2MSP.admin')"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  TwoOrgsOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *Org1
        - *Org2
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1
          - *Org2
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: 'ANY Readers'
      Writers:
        Type: ImplicitMeta
        Rule: 'ANY Writers'
      Admins:
        Type: ImplicitMeta
        Rule: 'MAJORITY Admins'

  TwoOrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
      Capabilities:
        <<: *ApplicationCapabilities
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin', 'Org2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org1MSP.peer', 'Org2MSP.peer')"
