version: '3'

services:
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:9998
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9998
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
    ports:
      - 7051:7051
      - 9998:9998
    networks:
      - net_default

  ccv_chaincode:
    container_name: ccv_chaincode
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CORE_CHAINCODE_ID_NAME=ccv
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_default
    networks:
      - net_default
    ports:
      - 9998:9998

networks:
  net_default:
    driver: bridge 