name: Fabric Network Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: |
          npm install
          cd fabric/chaincode/ccv
          npm install

      - name: Start Docker
        run: |
          sudo service docker start
          docker ps

      - name: Deploy Network
        run: |
          cd fabric/scripts
          ./deploy.sh

      - name: Run Tests
        run: |
          npm test
          npm run test:integration

      - name: Cleanup
        if: always()
        run: |
          cd fabric/scripts
          ./deploy.sh clean
