---
################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &OrdererOrg
        Name: OrdererMSP
        ID: OrdererMSP
        MSPDir: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        OrdererEndpoints:
            - orderer0.blockchain-simbiotica.com:7050
            - orderer1.blockchain-simbiotica.com:7051
            - orderer2.blockchain-simbiotica.com:7052
            - orderer3.blockchain-simbiotica.com:7053
            - orderer4.blockchain-simbiotica.com:7055

    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: ../../network/crypto-config/peerOrganizations/org1.blockchain-simbiotica.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org1MSP.peer')"
        AnchorPeers:
            - Host: peer0.org1.blockchain-simbiotica.com
              Port: 7061

    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: ../../network/crypto-config/peerOrganizations/org2.blockchain-simbiotica.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org2MSP.peer')"
        AnchorPeers:
            - Host: peer0.org2.blockchain-simbiotica.com
              Port: 9061

    - &Org3
        Name: Org3MSP
        ID: Org3MSP
        MSPDir: ../../network/crypto-config/peerOrganizations/org3.blockchain-simbiotica.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org3MSP.admin', 'Org3MSP.peer', 'Org3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org3MSP.admin', 'Org3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org3MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org3MSP.peer')"
        AnchorPeers:
            - Host: peer0.org3.blockchain-simbiotica.com
              Port: 11061

################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_5: true

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer0.blockchain-simbiotica.com:7050
        - orderer1.blockchain-simbiotica.com:7051
        - orderer2.blockchain-simbiotica.com:7052
        - orderer3.blockchain-simbiotica.com:7053
        - orderer4.blockchain-simbiotica.com:7055
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    EtcdRaft:
        Consenters:
            - Host: orderer0.blockchain-simbiotica.com
              Port: 7050
              ClientTLSCert: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/orderers/orderer0.blockchain-simbiotica.com/tls/server.crt
              ServerTLSCert: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/orderers/orderer0.blockchain-simbiotica.com/tls/server.crt
            - Host: orderer1.blockchain-simbiotica.com
              Port: 7051
              ClientTLSCert: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/orderers/orderer1.blockchain-simbiotica.com/tls/server.crt
              ServerTLSCert: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/orderers/orderer1.blockchain-simbiotica.com/tls/server.crt
            - Host: orderer2.blockchain-simbiotica.com
              Port: 7052
              ClientTLSCert: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/orderers/orderer2.blockchain-simbiotica.com/tls/server.crt
              ServerTLSCert: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/orderers/orderer2.blockchain-simbiotica.com/tls/server.crt
            - Host: orderer3.blockchain-simbiotica.com
              Port: 7053
              ClientTLSCert: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/orderers/orderer3.blockchain-simbiotica.com/tls/server.crt
              ServerTLSCert: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/orderers/orderer3.blockchain-simbiotica.com/tls/server.crt
            - Host: orderer4.blockchain-simbiotica.com
              Port: 7055
              ClientTLSCert: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/orderers/orderer4.blockchain-simbiotica.com/tls/server.crt
              ServerTLSCert: ../../network/crypto-config/ordererOrganizations/blockchain-simbiotica.com/orderers/orderer4.blockchain-simbiotica.com/tls/server.crt
        Options:
            TickInterval: 500ms
            ElectionTick: 10
            HeartbeatTick: 1
            MaxInflightBlocks: 5
            SnapshotIntervalSize: 16 MB
    Organizations:
        - *OrdererOrg
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   SECTION: Channel
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Profile
################################################################################
Profiles:
    SimbioticaOrdererGenesis: # Nombre del perfil del Génesis
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SimbioticaConsortium: # Nombre del Consorcio
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
    SimbioticaChannel: # Nombre del perfil del Canal
        Consortium: SimbioticaConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
            Capabilities:
                <<: *ApplicationCapabilities