# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definición de organizaciones que gestionan ordenadores
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Org1: Organización de ordenadores principal
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: blockchain-simbiotica.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" - Definición de hosts de ordenadores en la organización
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer0
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: orderer1
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: orderer2
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: orderer3
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: orderer4
        SANS:
          - localhost
          - 127.0.0.1

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definición de organizaciones que gestionan peers
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1: Primera organización de peers
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.blockchain-simbiotica.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" - Definición de hosts de peers en la organización
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: peer0
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: peer1
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: peer2
        SANS:
          - localhost
          - 127.0.0.1
    # ---------------------------------------------------------------------------
    # "Template" - Permite generar múltiples peers con nombres secuenciales
    # ---------------------------------------------------------------------------
    Template:
      Count: 0
      SANS:
        - localhost
        - 127.0.0.1
    # ---------------------------------------------------------------------------
    # "Users" - Usuarios adicionales a parte del Admin y User1
    # ---------------------------------------------------------------------------
    Users:
      Count: 3

  # ---------------------------------------------------------------------------
  # Org2: Segunda organización de peers
  # ---------------------------------------------------------------------------
  - Name: Org2
    Domain: org2.blockchain-simbiotica.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" - Definición de hosts de peers en la organización
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: peer0
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: peer1
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: peer2
        SANS:
          - localhost
          - 127.0.0.1
    Template:
      Count: 0
      SANS:
        - localhost
        - 127.0.0.1
    Users:
      Count: 3

  # ---------------------------------------------------------------------------
  # Org3: Tercera organización de peers
  # ---------------------------------------------------------------------------
  - Name: Org3
    Domain: org3.blockchain-simbiotica.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" - Definición de hosts de peers en la organización
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: peer0
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: peer1
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: peer2
        SANS:
          - localhost
          - 127.0.0.1
    Template:
      Count: 0
      SANS:
        - localhost
        - 127.0.0.1
    Users:
      Count: 3
